//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPrograV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int idFactura { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idMecanico { get; set; }
        public Nullable<int> idSolicitud { get; set; }
        public Nullable<decimal> Monto { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Mecanico Mecanico { get; set; }
        public virtual Solicitud Solicitud { get; set; }
    }
}
