//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPrograV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitud()
        {
            this.Facturas = new HashSet<Factura>();
        }
    
        public int idSolicitud { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idMecanico { get; set; }
        public Nullable<int> Estado { get; set; }
        public string Detalle { get; set; }
        public Nullable<int> idVehiculo { get; set; }
        public string Ubicacion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Facturas { get; set; }
        public virtual Mecanico Mecanico { get; set; }
    }
}
